# Site Settings
baseurl: ""
url : "https://isobelkeen.github.io/"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Isobel Keen
    description : Data Scientist #creator of Grape-Theme! Grape-Theme is my first jekyll theme and you can customize this theme easily.
    experience :
      - start : 2022-14-02
        end : 2025-23-01
        experience : Services Australia, Data Scientist
    skills : 
      - skill : Python & R & HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  isobel.keen@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  https://www.linkedin.com/in/isobel-keen/ # Full URL 
    github: isobelKeen
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
